// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiradorWebAPI.Context;

#nullable disable

namespace MiradorWebAPI.Migrations
{
    [DbContext(typeof(FUPContext))]
    partial class FUPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            //modelBuilder.Entity("MiradorWebAPI.DbModels.AtlasSysDefAll", b =>
            //    {
            //        b.Property<string>("Code00")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("code00");

            //        b.Property<string>("Arrondissement")
            //            .HasMaxLength(50)
            //            .HasColumnType("nvarchar(50)");

            //        b.Property<string>("Code01")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("code01");

            //        b.Property<string>("Code02")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("code02");

            //        b.Property<string>("Code03")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("code03");

            //        b.Property<string>("Code04")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("code04");

            //        b.Property<string>("Code05")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("code05");

            //        b.Property<string>("Code06")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("code06");

            //        b.Property<string>("CommunautéRurale")
            //            .HasMaxLength(50)
            //            .HasColumnType("nvarchar(50)")
            //            .HasColumnName("Communauté rurale");

            //        b.Property<string>("Commune")
            //            .HasMaxLength(50)
            //            .HasColumnType("nvarchar(50)");

            //        b.Property<string>("Département")
            //            .HasMaxLength(50)
            //            .HasColumnType("nvarchar(50)");

            //        b.Property<string>("Ia")
            //            .HasMaxLength(50)
            //            .HasColumnType("nvarchar(50)")
            //            .HasColumnName("IA");

            //        b.Property<string>("Iden")
            //            .HasMaxLength(50)
            //            .HasColumnType("nvarchar(50)")
            //            .HasColumnName("IDEN");

            //        b.HasKey("Code00");

            //        b.ToTable("ATLAS_SYS_DEF_ALL", (string)null);
            //    });

            //modelBuilder.Entity("MiradorWebAPI.DbModels.Enseignant", b =>
            //    {
            //        b.Property<int>("IdentifiantEnseignant")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("int")
            //            .HasColumnName("IDENTIFIANT_ENSEIGNANT");

            //        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentifiantEnseignant"), 1L, 1);

            //        b.Property<string>("Adresse")
            //            .HasMaxLength(150)
            //            .HasColumnType("nvarchar(150)")
            //            .HasColumnName("ADRESSE");

            //        b.Property<string>("Cni")
            //            .HasMaxLength(50)
            //            .HasColumnType("nvarchar(50)")
            //            .HasColumnName("CNI");

            //        b.Property<string>("CodeClasseTenue")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_CLASSE_TENUE");

            //        b.Property<string>("CodeCorps")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_CORPS");

            //        b.Property<string>("CodeDiplome")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_DIPLOME");

            //        b.Property<string>("CodeDiplomeProfessionnel")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_DIPLOME_PROFESSIONNEL");

            //        b.Property<string>("CodeEmployeur")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_EMPLOYEUR");

            //        b.Property<string>("CodeEtablissement")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("CODE_ETABLISSEMENT");

            //        b.Property<string>("CodeFonction")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_FONCTION");

            //        b.Property<string>("CodeGrade")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_GRADE");

            //        b.Property<string>("CodeLangue")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_LANGUE");

            //        b.Property<string>("CodeMatiere")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_MATIERE");

            //        b.Property<decimal?>("CodeMouvement")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT");

            //        b.Property<decimal?>("CodeMouvement2006")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2006");

            //        b.Property<decimal?>("CodeMouvement20071erMvmt")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2007_1erMvmt");

            //        b.Property<decimal?>("CodeMouvement20072emeMvmt")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2007_2emeMvmt");

            //        b.Property<decimal?>("CodeMouvement20081emeMvmt")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2008_1emeMvmt");

            //        b.Property<decimal?>("CodeMouvement20082emeMvmt")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2008_2emeMvmt");

            //        b.Property<decimal?>("CodeMouvement20091erMvmt")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2009_1erMvmt");

            //        b.Property<decimal?>("CodeMouvement2010")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2010");

            //        b.Property<decimal?>("CodeMouvement2011")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2011");

            //        b.Property<decimal?>("CodeMouvement2012")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2012");

            //        b.Property<decimal?>("CodeMouvement2014")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_MOUVEMENT_2014");

            //        b.Property<string>("CodeNationalite")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_NATIONALITE");

            //        b.Property<decimal?>("CodePiLangue")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_PI_LANGUE");

            //        b.Property<string>("CodePosition")
            //            .HasMaxLength(3)
            //            .IsUnicode(false)
            //            .HasColumnType("varchar(3)")
            //            .HasColumnName("CODE_POSITION");

            //        b.Property<string>("CodeSpecialite")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_SPECIALITE");

            //        b.Property<string>("CodeStatutPersonnel")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_STATUT_PERSONNEL");

            //        b.Property<string>("CodeTypePoste")
            //            .ValueGeneratedOnAdd()
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_TYPE_POSTE")
            //            .HasDefaultValueSql("((-99))");

            //        b.Property<string>("CodeTypeUtilisation")
            //            .IsRequired()
            //            .ValueGeneratedOnAdd()
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_TYPE_UTILISATION")
            //            .HasDefaultValueSql("('000')");

            //        b.Property<string>("CommentaireEnseignant")
            //            .HasMaxLength(200)
            //            .HasColumnType("nvarchar(200)")
            //            .HasColumnName("COMMENTAIRE_ENSEIGNANT");

            //        b.Property<string>("CreePar")
            //            .HasMaxLength(40)
            //            .HasColumnType("nvarchar(40)")
            //            .HasColumnName("CREE_PAR");

            //        b.Property<DateTime?>("DateCorps")
            //            .HasColumnType("datetime")
            //            .HasColumnName("DATE_CORPS");

            //        b.Property<DateTime?>("DateCreation")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("datetime")
            //            .HasColumnName("DATE_CREATION")
            //            .HasDefaultValueSql("(getdate())");

            //        b.Property<DateTime?>("DateDerniereModification")
            //            .HasColumnType("datetime")
            //            .HasColumnName("DATE_DERNIERE_MODIFICATION");

            //        b.Property<DateTime?>("DateEntreeEnseignementEnsei")
            //            .HasColumnType("smalldatetime")
            //            .HasColumnName("DATE_ENTREE_ENSEIGNEMENT_ENSEI");

            //        b.Property<DateTime?>("DateEntreeEtablissementEnse")
            //            .HasColumnType("smalldatetime")
            //            .HasColumnName("DATE_ENTREE_ETABLISSEMENT_ENSE");

            //        b.Property<DateTime?>("DateEntreeFonctionPublique")
            //            .HasColumnType("smalldatetime")
            //            .HasColumnName("DATE_ENTREE_FONCTION_PUBLIQUE_");

            //        b.Property<DateTime?>("DateInscriptionMirador")
            //            .HasColumnType("datetime")
            //            .HasColumnName("DATE_INSCRIPTION_MIRADOR");

            //        b.Property<DateTime?>("DateNaissEnseignant")
            //            .HasColumnType("smalldatetime")
            //            .HasColumnName("DATE_NAISS_ENSEIGNANT");

            //        b.Property<DateTime?>("DateObtentionDiplomeAca")
            //            .HasColumnType("datetime")
            //            .HasColumnName("DATE_OBTENTION_DIPLOME_ACA");

            //        b.Property<DateTime?>("DateObtentionDiplomePro")
            //            .HasColumnType("datetime")
            //            .HasColumnName("DATE_OBTENTION_DIPLOME_PRO");

            //        b.Property<bool?>("DeclarationPsv")
            //            .HasColumnType("bit")
            //            .HasColumnName("DECLARATION_PSV");

            //        b.Property<string>("EmailPro")
            //            .HasMaxLength(200)
            //            .HasColumnType("nvarchar(200)")
            //            .HasColumnName("EMAIL_PRO");

            //        b.Property<bool?>("EstBillingue")
            //            .HasColumnType("bit")
            //            .HasColumnName("EST_BILLINGUE");

            //        b.Property<string>("FupCodeCorps06")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("FUP_CODE_CORPS06");

            //        b.Property<string>("FupCodeCorps07")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("FUP_CODE_CORPS07");

            //        b.Property<string>("FupCodeCorps08")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("FUP_CODE_CORPS08");

            //        b.Property<string>("FupCodeGrade06")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("FUP_CODE_GRADE06");

            //        b.Property<string>("FupCodeGrade07")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("FUP_CODE_GRADE07");

            //        b.Property<string>("FupCodeGrade08")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("FUP_CODE_GRADE08");

            //        b.Property<int?>("IdentifiantEnseignantAxe")
            //            .HasColumnType("int")
            //            .HasColumnName("IDENTIFIANT_ENSEIGNANT_AXE");

            //        b.Property<decimal?>("IdentifiantEnseignantFup")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("IDENTIFIANT_ENSEIGNANT_FUP");

            //        b.Property<decimal?>("IdentifiantEnseignantPointage")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("IDENTIFIANT_ENSEIGNANT_POINTAGE");

            //        b.Property<string>("Ien")
            //            .HasMaxLength(10)
            //            .HasColumnType("nvarchar(10)")
            //            .HasColumnName("IEN");

            //        b.Property<string>("LieuNaissanceEnseignant")
            //            .HasMaxLength(200)
            //            .HasColumnType("nvarchar(200)")
            //            .HasColumnName("LIEU_NAISSANCE_ENSEIGNANT");

            //        b.Property<string>("MailEnseignant")
            //            .HasMaxLength(100)
            //            .HasColumnType("nvarchar(100)")
            //            .HasColumnName("MAIL_ENSEIGNANT");

            //        b.Property<string>("MailEnseignant2")
            //            .HasMaxLength(100)
            //            .HasColumnType("nvarchar(100)")
            //            .HasColumnName("MAIL_ENSEIGNANT2");

            //        b.Property<string>("MatriculeEnseignant")
            //            .IsRequired()
            //            .HasMaxLength(11)
            //            .HasColumnType("nvarchar(11)")
            //            .HasColumnName("MATRICULE_ENSEIGNANT");

            //        b.Property<decimal?>("MobileEnseignant")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("MOBILE_ENSEIGNANT");

            //        b.Property<decimal?>("MobileEnseignant2")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("MOBILE_ENSEIGNANT2");

            //        b.Property<string>("ModifiePar")
            //            .HasMaxLength(40)
            //            .HasColumnType("nvarchar(40)")
            //            .HasColumnName("MODIFIE_PAR");

            //        b.Property<bool?>("Mvt")
            //            .HasColumnType("bit")
            //            .HasColumnName("MVT");

            //        b.Property<short?>("NbHeuresAssures")
            //            .HasColumnType("smallint")
            //            .HasColumnName("NB_HEURES_ASSURES");

            //        b.Property<short?>("NbJourFormation")
            //            .HasColumnType("smallint")
            //            .HasColumnName("NB_JOUR_FORMATION");

            //        b.Property<decimal?>("NbreEnfants")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("NBRE_ENFANTS");

            //        b.Property<string>("NomEnseignant")
            //            .IsRequired()
            //            .HasMaxLength(30)
            //            .HasColumnType("nvarchar(30)")
            //            .HasColumnName("NOM_ENSEIGNANT");

            //        b.Property<bool?>("Ok")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("bit")
            //            .HasColumnName("OK")
            //            .HasDefaultValueSql("(0)");

            //        b.Property<string>("OldMatricule")
            //            .HasMaxLength(11)
            //            .HasColumnType("nvarchar(11)")
            //            .HasColumnName("OLD_MATRICULE");

            //        b.Property<string>("PasswordEnseignant")
            //            .HasMaxLength(100)
            //            .HasColumnType("nvarchar(100)")
            //            .HasColumnName("PASSWORD_ENSEIGNANT");

            //        b.Property<string>("PasswordValide")
            //            .HasMaxLength(10)
            //            .IsUnicode(false)
            //            .HasColumnType("char(10)")
            //            .HasColumnName("PASSWORD_VALIDE")
            //            .IsFixedLength();

            //        b.Property<string>("PrenomsEnseignant")
            //            .HasMaxLength(255)
            //            .HasColumnType("nvarchar(255)")
            //            .HasColumnName("PRENOMS_ENSEIGNANT");

            //        b.Property<string>("SexeEnseignant")
            //            .IsRequired()
            //            .HasMaxLength(1)
            //            .HasColumnType("nvarchar(1)")
            //            .HasColumnName("SEXE_ENSEIGNANT");

            //        b.Property<string>("SituationMatrimoniale")
            //            .HasMaxLength(15)
            //            .HasColumnType("nvarchar(15)")
            //            .HasColumnName("SITUATION_MATRIMONIALE");

            //        b.Property<string>("Status")
            //            .HasMaxLength(255)
            //            .IsUnicode(false)
            //            .HasColumnType("varchar(255)")
            //            .HasColumnName("STATUS");

            //        b.Property<int?>("VolumeHoraireDu")
            //            .HasColumnType("int")
            //            .HasColumnName("VOLUME_HORAIRE_DU");

            //        b.HasKey("IdentifiantEnseignant");

            //        b.HasIndex(new[] { "CodeCorps" }, "IX_CORPS");

            //        b.HasIndex(new[] { "MatriculeEnseignant" }, "IX_ENSEIGNANT")
            //            .IsUnique();

            //        b.HasIndex(new[] { "CodeCorps" }, "IX_ENSEIGNANT_1");

            //        SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex(new[] { "CodeCorps" }, "IX_ENSEIGNANT_1"), 90);

            //        b.HasIndex(new[] { "CodeEtablissement" }, "IX_ENSEIGNANT_2");

            //        SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex(new[] { "CodeEtablissement" }, "IX_ENSEIGNANT_2"), 90);

            //        b.HasIndex(new[] { "NomEnseignant", "PrenomsEnseignant" }, "idx_nom_prenom");

            //        b.ToTable("ENSEIGNANT", (string)null);
            //    });

            //modelBuilder.Entity("MiradorWebAPI.DbModels.EnseignantEtablissement", b =>
            //    {
            //        b.Property<int>("IdentifiantEnseignant")
            //            .HasColumnType("int")
            //            .HasColumnName("IDENTIFIANT_ENSEIGNANT");

            //        b.Property<string>("CodeEtablissement")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("CODE_ETABLISSEMENT");

            //        b.Property<string>("CodeAnnee")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_ANNEE");

            //        b.Property<string>("CodeSituation")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_SITUATION");

            //        b.Property<string>("CreePar")
            //            .ValueGeneratedOnAdd()
            //            .HasMaxLength(40)
            //            .IsUnicode(false)
            //            .HasColumnType("varchar(40)")
            //            .HasColumnName("CREE_PAR")
            //            .HasDefaultValueSql("(user_name())");

            //        b.Property<DateTime?>("DateCreation")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("datetime")
            //            .HasColumnName("DATE_CREATION")
            //            .HasDefaultValueSql("(getdate())");

            //        b.Property<DateTime?>("DateDerniereModification")
            //            .HasColumnType("datetime")
            //            .HasColumnName("DATE_DERNIERE_MODIFICATION");

            //        b.Property<string>("ModifiePar")
            //            .HasMaxLength(40)
            //            .IsUnicode(false)
            //            .HasColumnType("varchar(40)")
            //            .HasColumnName("MODIFIE_PAR");

            //        b.Property<int?>("NumeroOrdreEnseignant")
            //            .HasColumnType("int")
            //            .HasColumnName("NUMERO_ORDRE_ENSEIGNANT");

            //        b.Property<bool?>("Temp")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("bit")
            //            .HasDefaultValueSql("(0)");

            //        b.HasKey("IdentifiantEnseignant", "CodeEtablissement");

            //        b.HasIndex("CodeEtablissement");

            //        b.ToTable("ENSEIGNANT_ETABLISSEMENT", (string)null);
            //    });

            //modelBuilder.Entity("MiradorWebAPI.DbModels.Etablissement", b =>
            //    {
            //        b.Property<string>("CodeEtablissement")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("CODE_ETABLISSEMENT");

            //        b.Property<string>("Adresse")
            //            .HasMaxLength(30)
            //            .HasColumnType("nvarchar(30)")
            //            .HasColumnName("ADRESSE");

            //        b.Property<string>("BoitePostale")
            //            .HasMaxLength(5)
            //            .HasColumnType("nvarchar(5)")
            //            .HasColumnName("BOITE_POSTALE");

            //        b.Property<string>("CodeAdministratif")
            //            .HasMaxLength(15)
            //            .HasColumnType("nvarchar(15)")
            //            .HasColumnName("CODE_ADMINISTRATIF");

            //        b.Property<string>("CodeAdministratifOld")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("CODE_ADMINISTRATIF_old");

            //        b.Property<decimal?>("CodePi")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_PI");

            //        b.Property<decimal?>("CodePiLangue")
            //            .HasColumnType("numeric(18,0)")
            //            .HasColumnName("CODE_PI_LANGUE");

            //        b.Property<string>("CodeStatut")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_STATUT");

            //        b.Property<string>("CodeStatutPrive")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_STATUT_PRIVE");

            //        b.Property<string>("CodeSysteme")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_SYSTEME");

            //        b.Property<string>("CodeTypeEtablissement")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_TYPE_ETABLISSEMENT");

            //        b.Property<string>("CodeTypeSociologique")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_TYPE_SOCIOLOGIQUE");

            //        b.Property<string>("CodeTypeStructureAdm")
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("CODE_TYPE_STRUCTURE_ADM");

            //        b.Property<DateTime?>("DateCreation")
            //            .HasColumnType("smalldatetime")
            //            .HasColumnName("DATE_CREATION");

            //        b.Property<DateTime?>("DateReconnaissance")
            //            .HasColumnType("smalldatetime")
            //            .HasColumnName("DATE_RECONNAISSANCE");

            //        b.Property<string>("EcoleApplication")
            //            .ValueGeneratedOnAdd()
            //            .HasMaxLength(3)
            //            .HasColumnType("nvarchar(3)")
            //            .HasColumnName("ECOLE_APPLICATION")
            //            .HasDefaultValueSql("(N'Non')");

            //        b.Property<int?>("EstPrioriteBillingue")
            //            .HasColumnType("int")
            //            .HasColumnName("EST_PRIORITE_BILLINGUE");

            //        b.Property<bool?>("EtabPrioriteFemme")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("bit")
            //            .HasColumnName("ETAB_PRIORITE_FEMME")
            //            .HasDefaultValueSql("((0))");

            //        b.Property<string>("EtabVerrouille")
            //            .ValueGeneratedOnAdd()
            //            .HasMaxLength(1)
            //            .IsUnicode(false)
            //            .HasColumnType("char(1)")
            //            .HasColumnName("ETAB_VERROUILLE")
            //            .HasDefaultValueSql("('N')")
            //            .IsFixedLength();

            //        b.Property<string>("Mel")
            //            .HasMaxLength(30)
            //            .HasColumnType("nvarchar(30)")
            //            .HasColumnName("MEL");

            //        b.Property<int?>("NbClasse")
            //            .HasColumnType("int")
            //            .HasColumnName("NB_CLASSE");

            //        b.Property<string>("NomChefEtablissement")
            //            .HasMaxLength(40)
            //            .HasColumnType("nvarchar(40)")
            //            .HasColumnName("NOM_CHEF_ETABLISSEMENT");

            //        b.Property<string>("NomEtablissement")
            //            .HasMaxLength(50)
            //            .HasColumnType("nvarchar(50)")
            //            .HasColumnName("NOM_ETABLISSEMENT");

            //        b.Property<string>("OldCodeAdministratif")
            //            .HasMaxLength(15)
            //            .HasColumnType("nvarchar(15)")
            //            .HasColumnName("OLD_CODE_ADMINISTRATIF");

            //        b.Property<string>("OldNomEtablissement")
            //            .HasMaxLength(50)
            //            .HasColumnType("nvarchar(50)")
            //            .HasColumnName("OLD_NOM_ETABLISSEMENT");

            //        b.Property<string>("ReferenceAutorisation")
            //            .HasMaxLength(30)
            //            .HasColumnType("nvarchar(30)")
            //            .HasColumnName("REFERENCE_AUTORISATION");

            //        b.Property<string>("Telecopie")
            //            .HasMaxLength(12)
            //            .HasColumnType("nvarchar(12)")
            //            .HasColumnName("TELECOPIE");

            //        b.Property<string>("Telephone")
            //            .HasMaxLength(12)
            //            .HasColumnType("nvarchar(12)")
            //            .HasColumnName("TELEPHONE");

            //        b.HasKey("CodeEtablissement");

            //        b.HasIndex(new[] { "NomEtablissement" }, "IX_ETABLISSEMENT");

            //        SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex(new[] { "NomEtablissement" }, "IX_ETABLISSEMENT"), 90);

            //        b.ToTable("ETABLISSEMENT", (string)null);
            //    });

            //modelBuilder.Entity("MiradorWebAPI.DbModels.EtablissementRegroupement", b =>
            //    {
            //        b.Property<string>("CodeEtablissement")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("CODE_ETABLISSEMENT");

            //        b.Property<string>("CodeRegroupement")
            //            .HasMaxLength(6)
            //            .HasColumnType("nvarchar(6)")
            //            .HasColumnName("CODE_REGROUPEMENT");

            //        b.HasKey("CodeEtablissement", "CodeRegroupement");

            //        b.ToTable("ETABLISSEMENT_REGROUPEMENT", (string)null);
            //    });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            //modelBuilder.Entity("MiradorWebAPI.DbModels.EnseignantEtablissement", b =>
            //    {
            //        b.HasOne("MiradorWebAPI.DbModels.Etablissement", "CodeEtablissementNavigation")
            //            .WithMany("EnseignantEtablissements")
            //            .HasForeignKey("CodeEtablissement")
            //            .IsRequired()
            //            .HasConstraintName("FK_ENSEIGNANT_ETABLISSEMENT_ETABLISSEMENT");

            //        b.HasOne("MiradorWebAPI.DbModels.Enseignant", "IdentifiantEnseignantNavigation")
            //            .WithMany("EnseignantEtablissements")
            //            .HasForeignKey("IdentifiantEnseignant")
            //            .IsRequired()
            //            .HasConstraintName("FK_ENSEIGNANT_ETABLISSEMENT_ENSEIGNANT");

            //        b.Navigation("CodeEtablissementNavigation");

            //        b.Navigation("IdentifiantEnseignantNavigation");
            //    });

            //modelBuilder.Entity("MiradorWebAPI.DbModels.EtablissementRegroupement", b =>
            //    {
            //        b.HasOne("MiradorWebAPI.DbModels.Etablissement", "CodeEtablissementNavigation")
            //            .WithMany("EtablissementRegroupements")
            //            .HasForeignKey("CodeEtablissement")
            //            .IsRequired()
            //            .HasConstraintName("FK_ETABLISSEMENT_REGROUPEMENT_ETABLISSEMENT");

            //        b.Navigation("CodeEtablissementNavigation");
            //    });

            //modelBuilder.Entity("MiradorWebAPI.DbModels.Enseignant", b =>
            //    {
            //        b.Navigation("EnseignantEtablissements");
            //    });

            //modelBuilder.Entity("MiradorWebAPI.DbModels.Etablissement", b =>
            //    {
            //        b.Navigation("EnseignantEtablissements");

            //        b.Navigation("EtablissementRegroupements");
            //    });
#pragma warning restore 612, 618
        }
    }
}
